name: Scan Docker Image with Trivy

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          version: latest

      - name: Scan https://hub.docker.com/r/alpine/openssl image with Trivy
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL https://hub.docker.com/r/alpine/openssl
