name: Scan Docker Image with Trivy

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.5.3
        # with:
        #   version: latest  

      - name: Pull docker image
        run: docker pull alpine/openssl

      - name: Scanning image with trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL alpine/openssl
